//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tastehub.Core.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string Degree { get; set; }
        public string Institution { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public string Grade { get; set; }
    
        public virtual User User { get; set; }
    }
}
